feat: tofnd multisig client
axelarnetwork/ampd pull request #30
Opened 2023-06-23 15:26 UTC by haiyizxx

## Description
tofnd multisig client supports keygen, sign and key presence check

## Todos

- [ ] Unit tests
- [ ] Manual tests
- [ ] Documentation
- [ ] Connect epics/issues
- [ ] Tag type of change

## Steps to Test

## Expected Behaviour

## Other Notes

2023-06-24 03:18 UTC, cgorenflo requested changes

2023-06-24 03:18 UTC, cgorenflo commented on proto/tofnd/common.proto
> +    string key_uid = 1;
Edwin has marked key ids as uints in his multisig PR. We need to find common ground

2023-06-24 03:18 UTC, cgorenflo commented on proto/tofnd/common.proto
> +option go_package = "tofnd;tofnd";
I doubt you need a go package here

2023-06-24 03:18 UTC, cgorenflo commented on proto/tofnd/multisig.proto
> +option go_package = "tofnd;tofnd";
again, this is not go anymore

2023-06-24 03:18 UTC, cgorenflo commented on src/tofnd/client.rs
> +            .await
this seems to be an infinite call loop

2023-06-24 03:18 UTC, cgorenflo commented on src/tofnd/client.rs
> +};
are the generated files missing from this PR?

2023-06-24 03:18 UTC, cgorenflo commented on src/tofnd/client.rs
> +                    .map_err(|_| Report::from(Error::keygen("pubkey is invalid"))),
why discard the returned error?

2023-06-24 03:18 UTC, cgorenflo commented on src/tofnd/error.rs
> +}
why do you need those?

2023-06-24 03:18 UTC, cgorenflo commented on src/tofnd/error.rs
> +    Sign { message: String },
use attachments instead of adding the message string into the error message

2023-06-26 21:27 UTC, haiyizxx commented on src/tofnd/client.rs
> +};
`tonic-build` generates files at compile time, so won't need include the generated files

2023-06-26 21:30 UTC, haiyizxx commented on proto/tofnd/common.proto
> +option go_package = "tofnd;tofnd";
good call, pasted from tofnd. don't know why it has go option there as it's a rust package

2023-06-27 03:01 UTC, haiyizxx commented on proto/tofnd/common.proto
> +    string key_uid = 1;
I suggest we follow tofnd. use string for key id, to avoid unnecessary conversion

2023-06-28 20:50 UTC, cgorenflo approved these changes

2023-06-30 15:48 UTC, cgorenflo approved these changes

2023-06-30 15:48 UTC, cgorenflo commented on src/tofnd/client.rs
> +                    Report::from(Error::KeygenFailed).attach_printable(format!("{{ invalid value = {:?} }}", val))
```suggestion
                    Report::from(Error::KeygenFailed).attach_printable(format!("{{ invalid_value = {:?} }}", val))
```
since it's json I don't think space will fly here

2023-06-30 16:38 UTC, merged