fix: allow app exit when handle returns
axelarnetwork/ampd pull request #51
Opened 2023-08-11 00:29 UTC by haiyizxx

## Description

## Todos

- [ ] Unit tests
- [ ] Manual tests
- [ ] Documentation
- [ ] Connect epics/issues
- [ ] Tag type of change

## Steps to Test

## Expected Behaviour

## Other Notes

2023-08-11 20:06 UTC, cgorenflo approved these changes

2023-08-13 08:51 UTC, sammy1991106 requested changes

2023-08-13 08:51 UTC, sammy1991106 commented on src/report.rs
> +    Broadcast,
```suggestion
    Broadcaster,
```
just to match the name of the actual thing

2023-08-13 08:51 UTC, sammy1991106 commented on src/report.rs
> +        Error::Error(msg.to_string())
Is this still needed?

2023-08-13 08:51 UTC, sammy1991106 commented on src/lib.rs
> +        res
```suggestion
        let res = match (set.join_next().await, token.is_cancelled()) {
            (Some(result), false) => {
                token.cancel();

                result.map_err(Error::new).into_report().and_then(|result| result)
            }
            (_, true) => Ok(()),
            (None, _) => panic!("all tasks exited unexpectedly"),
        };

        while (set.join_next().await).is_some() {}

        res
```

2023-08-13 08:51 UTC, sammy1991106 commented on src/lib.rs
> +        res
1. Not a fan of mutation and always avoid when possible. 2. It's clearer this way that run returns an error iff the first task exits with an error and is not cancelled.

2023-08-16 17:51 UTC, haiyizxx commented on src/lib.rs
> +        res
like it

2023-08-16 18:28 UTC, sammy1991106 approved these changes

2023-08-16 18:40 UTC, merged