refactor: replace tofnd PublicKey with cosmrs::crypto::PublicKey
axelarnetwork/ampd pull request #62
Opened 2023-08-18 14:29 UTC by sammy1991106

## Description

## Todos

- [ ] Unit tests
- [ ] Manual tests
- [ ] Documentation
- [ ] Connect epics/issues
- [ ] Tag type of change

## Steps to Test

## Expected Behaviour

## Other Notes

2023-08-18 20:51 UTC, cgorenflo commented on src/tofnd/mod.rs
> +#[allow(non_snake_case)]
what's this for?

2023-08-18 20:51 UTC, cgorenflo approved these changes

2023-08-19 04:38 UTC, sammy1991106 commented on src/tofnd/mod.rs
> +#[allow(non_snake_case)]
The macro generates some non snakecase functions within and my vscode complains about it with warnings all the time.

2023-08-19 04:45 UTC, cgorenflo requested changes
the PR itself is ok, just move it over to the amplifier repo once ampd is merged in, otherwise I have to do the migration again

2023-08-21 22:58 UTC, closed without merging